version: 2

models:
  - name: dim_customers
    description: "Customers' names, addresses, and phone numbers."
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_employees
    description: "Employees' names, titles, and personal information."
    columns:
      - name: employee_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: fct_orders_detail
    description: "Details on products, quantities, and prices for each order in the Orders table."
    columns:
      - name: order_id
        description: ""
        tests:
          - not_null
      - name: product_id
        description: ""
        tests:
          - not_null
      - name: product_name
        description: ""
        tests:
          - not_null
      - name: supplier_id
        description: ""
        tests:
          - not_null
      - name: category_id
        description: ""
        tests:
          - not_null
      - name: unit_price
        description: ""
        tests:
          - not_null
      - name: quantity
        description: ""
        tests:
          - not_null
      - name: total
        description: ""
        tests:
          - not_null
      - name: discount
        description: ""
        tests:
          - not_null